export {
  insertEnquiry,
  insertProperty,
  newId,
  nextEnquiryReference,
  nextPropertyReference,
  patchEnquiry,
  patchProperty,
  removeEnquiry,
  removeProperty,
  resetStore,
  selectEnquiries,
  selectEnquiry,
  selectProperties,
  selectProperty,
  stampsForEnquiryStatus,
} from "./db";
