/**
 * Seed data for the demo.
 *
 * Everything here is invented: no real owners, no real deeds, no real phone
 * numbers (every mobile is in the 05x 000 0xxx block nobody uses). Districts,
 * street types and price brackets follow the north-Riyadh market closely enough
 * that the agency recognises its own stock when it sees the screen.
 *
 * Prices are whole riyals. A sale price is the total; a rent price is what one
 * period costs, and Riyadh quotes residential rent by the year — so most units
 * carry `rentPeriod: "yearly"` and only the short-let furnished ones are
 * monthly.
 */

import { addHours, subDays, subHours, subMinutes } from "date-fns";

import type {
  Amenity,
  ContactPreference,
  District,
  Enquiry,
  EnquirySource,
  EnquiryStatus,
  Property,
  PropertyStatus,
  PropertyType,
  RentPeriod,
  TransactionType,
} from "@/types";

interface RawProperty {
  reference: string;
  type: PropertyType;
  transaction: TransactionType;
  district: District;
  status: PropertyStatus;
  priceSar: number;
  rentPeriod?: RentPeriod;
  areaSqm: number;
  beds: number;
  baths: number;
  livingRooms: number;
  floor?: number;
  ageYears: number;
  furnished?: boolean;
  featured?: boolean;
  amenities: Amenity[];
  titleAr: string;
  titleEn: string;
  descriptionAr: string;
  descriptionEn: string;
  /** How long the unit has been on the books. */
  daysAgo: number;
  viewsThisWeek: number;
}

const RAW_PROPERTIES: RawProperty[] = [
  {
    reference: "GZ-1042",
    type: "apartment",
    transaction: "sale",
    district: "narjis",
    status: "available",
    priceSar: 1_150_000,
    areaSqm: 168,
    beds: 3,
    baths: 3,
    livingRooms: 1,
    floor: 2,
    ageYears: 1,
    featured: true,
    amenities: [
      "elevator",
      "parking",
      "private-entrance",
      "fitted-kitchen",
      "near-mosque",
      "central-ac",
    ],
    titleAr: "شقة ٣ غرف بمدخلين — النرجس",
    titleEn: "Three-bedroom apartment, two entrances — Al Narjis",
    descriptionAr:
      "الدور الثاني في عمارة عمرها سنة على شارع ٢٠ شمالي. ثلاث غرف وصالة ومطبخ راكب، ومدخلين منفصلين. مواقف داخل السور والمسجد على بعد دقيقتين مشي.",
    descriptionEn:
      "Second floor of a one-year-old building on a 20 m street facing north. Three bedrooms, a living room, a fitted kitchen and two separate entrances. Parking inside the wall, mosque two minutes away.",
    daysAgo: 4,
    viewsThisWeek: 214,
  },
  {
    reference: "GZ-1043",
    type: "apartment",
    transaction: "rent",
    district: "yasmin",
    status: "available",
    priceSar: 68_000,
    rentPeriod: "yearly",
    areaSqm: 145,
    beds: 3,
    baths: 2,
    livingRooms: 1,
    floor: 3,
    ageYears: 3,
    amenities: ["elevator", "parking", "balcony", "near-school", "central-ac"],
    titleAr: "شقة للإيجار السنوي — الياسمين",
    titleEn: "Apartment for annual rent — Al Yasmin",
    descriptionAr:
      "شقة عائلية في الدور الثالث، مكيفات مركزية وشرفة على الشارع الخلفي الهادئ. المدارس والبقالة في نفس البلوك، والإيجار يُدفع على دفعتين.",
    descriptionEn:
      "A family unit on the third floor with central A/C and a balcony over the quiet back street. Schools and shops on the same block; rent payable in two instalments.",
    daysAgo: 9,
    viewsThisWeek: 168,
  },
  {
    reference: "GZ-1044",
    type: "villa",
    transaction: "sale",
    district: "malqa",
    status: "available",
    priceSar: 2_850_000,
    areaSqm: 400,
    beds: 5,
    baths: 6,
    livingRooms: 2,
    ageYears: 2,
    featured: true,
    amenities: [
      "parking",
      "garden",
      "maid-room",
      "driver-room",
      "roof-annex",
      "two-entrances",
      "central-ac",
    ],
    titleAr: "فيلا درج داخلي وملحق — الملقا",
    titleEn: "Villa with internal stair and roof annex — Al Malqa",
    descriptionAr:
      "فيلا زاوية على شارعين، درج داخلي وملحق سطح مستقل بمدخله الخاص. غرفة خادمة وغرفة سائق وحوش خلفي مشجّر. الصك جاهز والإفراغ فوري.",
    descriptionEn:
      "A corner villa on two streets, with an internal stair and a roof annex that has its own entrance. Maid's and driver's rooms, and a planted back yard. Deed is clear and transfer is immediate.",
    daysAgo: 12,
    viewsThisWeek: 341,
  },
  {
    reference: "GZ-1045",
    type: "floor",
    transaction: "sale",
    district: "narjis",
    status: "reserved",
    priceSar: 1_650_000,
    areaSqm: 290,
    beds: 4,
    baths: 4,
    livingRooms: 2,
    floor: 1,
    ageYears: 0,
    amenities: [
      "private-entrance",
      "parking",
      "maid-room",
      "new-build",
      "central-ac",
      "near-mosque",
    ],
    titleAr: "دور أول بمدخل مستقل — النرجس",
    titleEn: "First floor with its own entrance — Al Narjis",
    descriptionAr:
      "دور جديد لم يُسكن، مدخل وحوش مستقلين وأربع غرف. التشطيب أبيض وسيراميك كبير، والعداد مفصول عن الدور الأرضي.",
    descriptionEn:
      "A new floor, never occupied, with its own entrance and yard and four bedrooms. White finish and large-format tile; the meter is separate from the ground floor.",
    daysAgo: 6,
    viewsThisWeek: 187,
  },
  {
    reference: "GZ-1046",
    type: "land",
    transaction: "sale",
    district: "arid",
    status: "available",
    priceSar: 1_980_000,
    areaSqm: 600,
    beds: 0,
    baths: 0,
    livingRooms: 0,
    ageYears: 0,
    amenities: ["two-entrances"],
    titleAr: "أرض سكنية ٦٠٠ م² — العارض",
    titleEn: "Residential plot, 600 m² — Al Arid",
    descriptionAr:
      "أرض على شارع ١٥ جنوبي، الطول ٢٠ والعرض ٣٠، والمخطط مخدوم بالكامل. السعر ٣٬٣٠٠ للمتر وقابل للتفاوض على الجاد.",
    descriptionEn:
      "A plot on a 15 m street facing south, 20 × 30, in a fully serviced block. Priced at 3,300 per m², negotiable for a serious buyer.",
    daysAgo: 18,
    viewsThisWeek: 96,
  },
  {
    reference: "GZ-1047",
    type: "commercial",
    transaction: "rent",
    district: "sahafah",
    status: "available",
    priceSar: 140_000,
    rentPeriod: "yearly",
    areaSqm: 120,
    beds: 0,
    baths: 1,
    livingRooms: 0,
    ageYears: 4,
    amenities: ["parking", "two-entrances", "central-ac", "security"],
    titleAr: "محل على شارع تجاري — الصحافة",
    titleEn: "Shop on a commercial street — Al Sahafah",
    descriptionAr:
      "محل بواجهة ٨ أمتار على شارع تجاري حيّ، مع دورة مياه ومخزن خلفي. مناسب لمقهى أو صيدلية، والرخصة البلدية سارية.",
    descriptionEn:
      "An 8 m frontage on a busy commercial street, with a WC and a back store. Suits a café or a pharmacy; the municipal licence is current.",
    daysAgo: 21,
    viewsThisWeek: 74,
  },
  {
    reference: "GZ-1048",
    type: "apartment",
    transaction: "sale",
    district: "yasmin",
    status: "sold",
    priceSar: 980_000,
    areaSqm: 152,
    beds: 3,
    baths: 2,
    livingRooms: 1,
    floor: 1,
    ageYears: 5,
    amenities: ["elevator", "parking", "fitted-kitchen", "near-school"],
    titleAr: "شقة ٣ غرف — الياسمين",
    titleEn: "Three-bedroom apartment — Al Yasmin",
    descriptionAr:
      "شقة في الدور الأول بعمارة هادئة، مطبخ راكب وموقف مظلل. انباعت خلال أسبوعين من عرضها.",
    descriptionEn:
      "A first-floor unit in a quiet building, with a fitted kitchen and a shaded parking bay. It sold within two weeks of listing.",
    daysAgo: 34,
    viewsThisWeek: 41,
  },
  {
    reference: "GZ-1049",
    type: "apartment",
    transaction: "rent",
    district: "narjis",
    status: "rented",
    priceSar: 6_800,
    rentPeriod: "monthly",
    areaSqm: 95,
    beds: 2,
    baths: 2,
    livingRooms: 1,
    floor: 4,
    ageYears: 2,
    furnished: true,
    amenities: ["elevator", "parking", "balcony", "central-ac", "security"],
    titleAr: "شقة مفروشة إيجار شهري — النرجس",
    titleEn: "Furnished apartment, monthly rent — Al Narjis",
    descriptionAr:
      "شقة مفروشة بالكامل بعقد شهري، مناسبة للمبتعثين وموظفي الشركات. الفواتير على المستأجر والحد الأدنى ثلاثة أشهر.",
    descriptionEn:
      "Fully furnished on a monthly contract, suited to people here for work or study. Utilities on the tenant; three-month minimum.",
    daysAgo: 27,
    viewsThisWeek: 58,
  },
  {
    reference: "GZ-1050",
    type: "villa",
    transaction: "rent",
    district: "hittin",
    status: "available",
    priceSar: 190_000,
    rentPeriod: "yearly",
    areaSqm: 420,
    beds: 5,
    baths: 5,
    livingRooms: 2,
    ageYears: 6,
    amenities: [
      "parking",
      "garden",
      "pool",
      "maid-room",
      "security",
      "central-ac",
    ],
    titleAr: "فيلا بمسبح للإيجار السنوي — حطين",
    titleEn: "Villa with a pool, annual rent — Hittin",
    descriptionAr:
      "فيلا داخل مجمع مسوّر بحراسة، مسبح خاص وحديقة أمامية. الصيانة على المالك والإيجار سنوي على دفعتين.",
    descriptionEn:
      "Inside a walled compound with security, with a private pool and a front garden. Maintenance sits with the owner; annual rent in two instalments.",
    daysAgo: 15,
    viewsThisWeek: 203,
  },
  {
    reference: "GZ-1051",
    type: "floor",
    transaction: "rent",
    district: "qirawan",
    status: "available",
    priceSar: 85_000,
    rentPeriod: "yearly",
    areaSqm: 260,
    beds: 4,
    baths: 3,
    livingRooms: 2,
    floor: 2,
    ageYears: 4,
    amenities: ["private-entrance", "parking", "central-ac", "near-mosque"],
    titleAr: "دور علوي للإيجار — القيروان",
    titleEn: "Upper floor for rent — Al Qirawan",
    descriptionAr:
      "دور علوي بمدخل مستقل ودرج خارجي، أربع غرف وصالتين. الحي هادئ والمخرج على الدائري الشمالي قريب.",
    descriptionEn:
      "An upper floor with its own entrance and outside stair, four bedrooms and two living rooms. A quiet district with a quick run to the Northern Ring.",
    daysAgo: 11,
    viewsThisWeek: 129,
  },
  {
    reference: "GZ-1052",
    type: "apartment",
    transaction: "sale",
    district: "qirawan",
    status: "available",
    priceSar: 795_000,
    areaSqm: 140,
    beds: 3,
    baths: 2,
    livingRooms: 1,
    floor: 1,
    ageYears: 0,
    amenities: ["elevator", "parking", "new-build", "fitted-kitchen"],
    titleAr: "شقة جديدة بسعر مناسب — القيروان",
    titleEn: "New apartment at a fair price — Al Qirawan",
    descriptionAr:
      "شقة تسليم جديد في مشروع من ست شقق. التشطيب بسيط ونظيف، والسعر أقل من متوسط الحي بحكم البعد عن الشارع التجاري.",
    descriptionEn:
      "Handover-new in a six-unit project. A plain, clean finish, priced under the district average because it sits away from the commercial street.",
    daysAgo: 3,
    viewsThisWeek: 152,
  },
  {
    reference: "GZ-1053",
    type: "land",
    transaction: "sale",
    district: "narjis",
    status: "available",
    priceSar: 2_640_000,
    areaSqm: 800,
    beds: 0,
    baths: 0,
    livingRooms: 0,
    ageYears: 0,
    amenities: ["two-entrances"],
    titleAr: "أرض زاوية ٨٠٠ م² — النرجس",
    titleEn: "Corner plot, 800 m² — Al Narjis",
    descriptionAr:
      "أرض زاوية على شارعين ٢٠ و١٥، تصلح لفيلتين أو عمارة سكنية حسب الاشتراطات. ٣٬٣٠٠ للمتر.",
    descriptionEn:
      "A corner plot on 20 m and 15 m streets, big enough for two villas or a residential building under the current rules. 3,300 per m².",
    daysAgo: 25,
    viewsThisWeek: 118,
  },
  {
    reference: "GZ-1054",
    type: "villa",
    transaction: "sale",
    district: "arid",
    status: "available",
    priceSar: 2_150_000,
    areaSqm: 375,
    beds: 5,
    baths: 5,
    livingRooms: 2,
    ageYears: 0,
    amenities: [
      "parking",
      "maid-room",
      "roof-annex",
      "new-build",
      "central-ac",
      "near-mosque",
    ],
    titleAr: "فيلا جديدة بملحق — العارض",
    titleEn: "New villa with annex — Al Arid",
    descriptionAr:
      "فيلا تسليم جديد بملحق سطح وغرفة خادمة. المخطط جديد والخدمات كاملة، والسعر أفضل من الملقا لنفس المساحة.",
    descriptionEn:
      "Handover-new, with a roof annex and a maid's room. A new block with full services, and better value than Al Malqa for the same area.",
    daysAgo: 8,
    viewsThisWeek: 176,
  },
  {
    reference: "GZ-1055",
    type: "apartment",
    transaction: "sale",
    district: "malqa",
    status: "available",
    priceSar: 1_420_000,
    areaSqm: 178,
    beds: 3,
    baths: 3,
    livingRooms: 2,
    floor: 3,
    ageYears: 1,
    featured: true,
    amenities: [
      "elevator",
      "parking",
      "balcony",
      "fitted-kitchen",
      "security",
      "central-ac",
    ],
    titleAr: "شقة بإطلالة على الحديقة — الملقا",
    titleEn: "Apartment over the park — Al Malqa",
    descriptionAr:
      "الدور الثالث بواجهة على حديقة الحي، صالتين وثلاث غرف وشرفة طويلة. العمارة فيها حارس ومصعد وموقفين للشقة.",
    descriptionEn:
      "Third floor facing the neighbourhood park, with two living rooms, three bedrooms and a long balcony. The building has a caretaker, a lift and two bays per unit.",
    daysAgo: 5,
    viewsThisWeek: 288,
  },
  {
    reference: "GZ-1056",
    type: "floor",
    transaction: "sale",
    district: "yasmin",
    status: "available",
    priceSar: 1_380_000,
    areaSqm: 275,
    beds: 4,
    baths: 3,
    livingRooms: 2,
    floor: 2,
    ageYears: 3,
    amenities: ["private-entrance", "parking", "central-ac", "near-school"],
    titleAr: "دور علوي ٤ غرف — الياسمين",
    titleEn: "Upper floor, four bedrooms — Al Yasmin",
    descriptionAr:
      "دور علوي بمدخل مستقل في فيلا دورين، الشارع ١٥ والاتجاه شمالي. المدرسة الابتدائية على بعد شارعين.",
    descriptionEn:
      "An upper floor with its own entrance in a two-storey villa, on a 15 m street facing north. The primary school is two streets away.",
    daysAgo: 14,
    viewsThisWeek: 143,
  },
  {
    reference: "GZ-1057",
    type: "apartment",
    transaction: "rent",
    district: "sahafah",
    status: "available",
    priceSar: 72_000,
    rentPeriod: "yearly",
    areaSqm: 150,
    beds: 3,
    baths: 2,
    livingRooms: 1,
    floor: 2,
    ageYears: 2,
    amenities: ["elevator", "parking", "central-ac", "fitted-kitchen"],
    titleAr: "شقة ٣ غرف قريبة من الخدمات — الصحافة",
    titleEn: "Three-bedroom near the shops — Al Sahafah",
    descriptionAr:
      "شقة نظيفة في عمارة صغيرة، مطبخ راكب ومكيفات مركزية. السوق والصيدلية على الشارع نفسه.",
    descriptionEn:
      "A clean unit in a small building, with a fitted kitchen and central A/C. The supermarket and pharmacy are on the same street.",
    daysAgo: 7,
    viewsThisWeek: 134,
  },
  {
    reference: "GZ-1058",
    type: "commercial",
    transaction: "sale",
    district: "rabie",
    status: "available",
    priceSar: 3_200_000,
    areaSqm: 240,
    beds: 0,
    baths: 2,
    livingRooms: 0,
    ageYears: 7,
    amenities: ["parking", "two-entrances", "security"],
    titleAr: "معرض تجاري على شارع رئيسي — الربيع",
    titleEn: "Showroom on a main street — Al Rabie",
    descriptionAr:
      "معرض بواجهة زجاجية ١٢ مترًا ومواقف أمامية، مؤجر حاليًا بعقد ينتهي بعد ثمانية أشهر. العائد الحالي ٧٪.",
    descriptionEn:
      "A 12 m glass frontage with parking in front, currently let on a contract that ends in eight months. The running yield is 7%.",
    daysAgo: 30,
    viewsThisWeek: 88,
  },
  {
    reference: "GZ-1059",
    type: "apartment",
    transaction: "sale",
    district: "rabie",
    status: "available",
    priceSar: 865_000,
    areaSqm: 138,
    beds: 3,
    baths: 2,
    livingRooms: 1,
    floor: 4,
    ageYears: 6,
    amenities: ["elevator", "parking", "balcony", "near-mosque"],
    titleAr: "شقة بسعر مناسب للاستثمار — الربيع",
    titleEn: "Apartment priced for an investor — Al Rabie",
    descriptionAr:
      "شقة في الدور الرابع، مؤجرة حاليًا بـ ٤٨ ألف سنويًا. مناسبة لمن يبي دخل جاهز من أول شهر.",
    descriptionEn:
      "A fourth-floor unit currently let at 48,000 a year. Suits a buyer who wants income from the first month.",
    daysAgo: 19,
    viewsThisWeek: 67,
  },
  {
    reference: "GZ-1060",
    type: "villa",
    transaction: "sale",
    district: "narjis",
    status: "reserved",
    priceSar: 3_450_000,
    areaSqm: 450,
    beds: 6,
    baths: 7,
    livingRooms: 3,
    ageYears: 1,
    featured: true,
    amenities: [
      "parking",
      "garden",
      "pool",
      "maid-room",
      "driver-room",
      "roof-annex",
      "basement",
      "central-ac",
    ],
    titleAr: "فيلا ٦ غرف بقبو ومسبح — النرجس",
    titleEn: "Six-bedroom villa, basement and pool — Al Narjis",
    descriptionAr:
      "أكبر ما عندنا في النرجس: ست غرف وقبو مجهز ومسبح داخلي، وملحق سطح مستقل. محجوزة الآن وفيه قائمة انتظار.",
    descriptionEn:
      "The largest thing we hold in Al Narjis: six bedrooms, a finished basement, an indoor pool and a separate roof annex. Reserved right now, with a waiting list.",
    daysAgo: 22,
    viewsThisWeek: 396,
  },
  {
    reference: "GZ-1061",
    type: "apartment",
    transaction: "rent",
    district: "malqa",
    status: "available",
    priceSar: 96_000,
    rentPeriod: "yearly",
    areaSqm: 165,
    beds: 3,
    baths: 3,
    livingRooms: 2,
    floor: 5,
    ageYears: 1,
    amenities: [
      "elevator",
      "parking",
      "balcony",
      "security",
      "central-ac",
      "fitted-kitchen",
    ],
    titleAr: "شقة دور خامس بإطلالة — الملقا",
    titleEn: "Fifth-floor apartment with a view — Al Malqa",
    descriptionAr:
      "الدور الأخير في عمارة حديثة، إطلالة مفتوحة وشرفتين. الإيجار سنوي ويشمل الصيانة والحارس.",
    descriptionEn:
      "Top floor of a recent building, with an open outlook and two balconies. Annual rent, covering maintenance and the caretaker.",
    daysAgo: 10,
    viewsThisWeek: 181,
  },
  {
    reference: "GZ-1062",
    type: "floor",
    transaction: "rent",
    district: "narjis",
    status: "available",
    priceSar: 78_000,
    rentPeriod: "yearly",
    areaSqm: 240,
    beds: 4,
    baths: 3,
    livingRooms: 2,
    floor: 1,
    ageYears: 5,
    amenities: ["private-entrance", "parking", "central-ac", "near-school"],
    titleAr: "دور أرضي بحوش — النرجس",
    titleEn: "Ground floor with a yard — Al Narjis",
    descriptionAr:
      "دور أرضي بحوش أمامي ومدخل مستقل، مناسب لعائلة فيها أطفال. العداد مفصول والصيانة على المالك.",
    descriptionEn:
      "A ground floor with a front yard and its own entrance, right for a family with young children. Separate meter; maintenance sits with the owner.",
    daysAgo: 13,
    viewsThisWeek: 157,
  },
  {
    reference: "GZ-1063",
    type: "land",
    transaction: "sale",
    district: "qirawan",
    status: "available",
    priceSar: 1_120_000,
    areaSqm: 480,
    beds: 0,
    baths: 0,
    livingRooms: 0,
    ageYears: 0,
    amenities: [],
    titleAr: "أرض ٤٨٠ م² في مخطط جديد — القيروان",
    titleEn: "480 m² plot in a new block — Al Qirawan",
    descriptionAr:
      "أرض على شارع ١٥، السفلتة والإنارة تمت والصرف قادم خلال السنة. ٢٬٣٣٣ للمتر.",
    descriptionEn:
      "On a 15 m street; asphalt and lighting are done and drainage lands within the year. 2,333 per m².",
    daysAgo: 28,
    viewsThisWeek: 62,
  },
  {
    reference: "GZ-1064",
    type: "apartment",
    transaction: "sale",
    district: "hittin",
    status: "available",
    priceSar: 1_260_000,
    areaSqm: 160,
    beds: 3,
    baths: 3,
    livingRooms: 1,
    floor: 2,
    ageYears: 2,
    amenities: [
      "elevator",
      "parking",
      "security",
      "central-ac",
      "fitted-kitchen",
    ],
    titleAr: "شقة في مجمع مسوّر — حطين",
    titleEn: "Apartment in a gated block — Hittin",
    descriptionAr:
      "شقة داخل مجمع فيه حراسة ومواقف مظللة. تشطيب فوق المتوسط والمطبخ راكب بالكامل.",
    descriptionEn:
      "Inside a gated block with security and shaded parking. Finish is above average and the kitchen is fully fitted.",
    daysAgo: 16,
    viewsThisWeek: 121,
  },
  {
    reference: "GZ-1065",
    type: "villa",
    transaction: "rent",
    district: "malqa",
    status: "rented",
    priceSar: 210_000,
    rentPeriod: "yearly",
    areaSqm: 430,
    beds: 5,
    baths: 6,
    livingRooms: 2,
    ageYears: 3,
    amenities: ["parking", "garden", "maid-room", "driver-room", "central-ac"],
    titleAr: "فيلا عائلية للإيجار — الملقا",
    titleEn: "Family villa for rent — Al Malqa",
    descriptionAr:
      "فيلا بخمس غرف وحديقة خلفية، تأجرت لثلاث سنوات. نضيفك في قائمة الانتظار إذا كنت تبي شبيهها.",
    descriptionEn:
      "Five bedrooms and a back garden, let on a three-year contract. We can add you to the waiting list for something similar.",
    daysAgo: 41,
    viewsThisWeek: 44,
  },
  {
    reference: "GZ-1066",
    type: "apartment",
    transaction: "sale",
    district: "sahafah",
    status: "available",
    priceSar: 1_050_000,
    areaSqm: 155,
    beds: 3,
    baths: 2,
    livingRooms: 1,
    floor: 1,
    ageYears: 4,
    amenities: ["elevator", "parking", "balcony", "near-school", "central-ac"],
    titleAr: "شقة ٣ غرف قريبة من المدارس — الصحافة",
    titleEn: "Three-bedroom near the schools — Al Sahafah",
    descriptionAr:
      "الدور الأول في عمارة من ثماني شقق، الشارع هادئ ومدرستان في نفس الحي. مناسبة لأول تملّك.",
    descriptionEn:
      "First floor in an eight-unit building on a quiet street, with two schools in the district. A sensible first purchase.",
    daysAgo: 2,
    viewsThisWeek: 199,
  },
  {
    reference: "GZ-1067",
    type: "commercial",
    transaction: "rent",
    district: "narjis",
    status: "available",
    priceSar: 96_000,
    rentPeriod: "yearly",
    areaSqm: 85,
    beds: 0,
    baths: 1,
    livingRooms: 0,
    ageYears: 1,
    amenities: ["parking", "central-ac", "new-build"],
    titleAr: "محل جديد بواجهة ٦ م — النرجس",
    titleEn: "New shop, 6 m frontage — Al Narjis",
    descriptionAr:
      "محل تسليم جديد في مجمع تجاري صغير على شارع أنس بن مالك. مناسب لعيادة أسنان أو صالون.",
    descriptionEn:
      "Handover-new in a small commercial block on Anas Ibn Malik Road. Suits a dental clinic or a salon.",
    daysAgo: 6,
    viewsThisWeek: 93,
  },
  {
    reference: "GZ-1068",
    type: "apartment",
    transaction: "rent",
    district: "arid",
    status: "available",
    priceSar: 52_000,
    rentPeriod: "yearly",
    areaSqm: 130,
    beds: 2,
    baths: 2,
    livingRooms: 1,
    floor: 2,
    ageYears: 1,
    amenities: ["elevator", "parking", "central-ac", "near-mosque"],
    titleAr: "شقة غرفتين بإيجار مناسب — العارض",
    titleEn: "Two-bedroom at a fair rent — Al Arid",
    descriptionAr:
      "شقة صغيرة نظيفة في عمارة جديدة، مناسبة لأسرة صغيرة أو موظف. الإيجار أقل من متوسط شمال الرياض.",
    descriptionEn:
      "A small, clean unit in a new building — right for a couple or someone here for work. Rent sits below the north-Riyadh average.",
    daysAgo: 1,
    viewsThisWeek: 147,
  },
  {
    reference: "GZ-1069",
    type: "floor",
    transaction: "sale",
    district: "malqa",
    status: "sold",
    priceSar: 1_760_000,
    areaSqm: 300,
    beds: 4,
    baths: 4,
    livingRooms: 2,
    floor: 1,
    ageYears: 2,
    amenities: ["private-entrance", "parking", "maid-room", "central-ac"],
    titleAr: "دور أول بمدخل مستقل — الملقا",
    titleEn: "First floor, own entrance — Al Malqa",
    descriptionAr:
      "دور واسع بأربع غرف وغرفة خادمة. انباع الشهر الماضي بعد معاينتين.",
    descriptionEn:
      "A wide floor with four bedrooms and a maid's room. Sold last month after two viewings.",
    daysAgo: 46,
    viewsThisWeek: 29,
  },
  {
    reference: "GZ-1070",
    type: "land",
    transaction: "sale",
    district: "rabie",
    status: "available",
    priceSar: 2_280_000,
    areaSqm: 720,
    beds: 0,
    baths: 0,
    livingRooms: 0,
    ageYears: 0,
    amenities: ["two-entrances"],
    titleAr: "أرض تجارية سكنية ٧٢٠ م² — الربيع",
    titleEn: "Mixed-use plot, 720 m² — Al Rabie",
    descriptionAr:
      "أرض على شارعين، الاشتراطات تسمح بتجاري في الدور الأرضي وسكني فوقه. ٣٬١٦٧ للمتر.",
    descriptionEn:
      "On two streets, with rules allowing retail at ground level and residential above. 3,167 per m².",
    daysAgo: 24,
    viewsThisWeek: 79,
  },
  {
    reference: "GZ-1071",
    type: "apartment",
    transaction: "sale",
    district: "narjis",
    status: "available",
    priceSar: 1_090_000,
    areaSqm: 162,
    beds: 3,
    baths: 3,
    livingRooms: 1,
    floor: 3,
    ageYears: 0,
    featured: true,
    amenities: [
      "elevator",
      "parking",
      "new-build",
      "fitted-kitchen",
      "balcony",
      "central-ac",
    ],
    titleAr: "شقة تسليم جديد — النرجس",
    titleEn: "Handover-new apartment — Al Narjis",
    descriptionAr:
      "شقة لم تُسكن في عمارة سلّمت هذا الشهر. ثلاث غرف ومطبخ راكب وشرفة، والضمان على المقاول سنتين.",
    descriptionEn:
      "Never occupied, in a building handed over this month. Three bedrooms, a fitted kitchen and a balcony, with a two-year contractor warranty.",
    daysAgo: 1,
    viewsThisWeek: 265,
  },
  {
    reference: "GZ-1072",
    type: "villa",
    transaction: "sale",
    district: "yasmin",
    status: "available",
    priceSar: 2_690_000,
    areaSqm: 390,
    beds: 5,
    baths: 5,
    livingRooms: 2,
    ageYears: 4,
    amenities: [
      "parking",
      "garden",
      "maid-room",
      "roof-annex",
      "near-mosque",
      "central-ac",
    ],
    titleAr: "فيلا درج داخلي — الياسمين",
    titleEn: "Villa with internal stair — Al Yasmin",
    descriptionAr:
      "فيلا على شارع ١٥ غربي، درج داخلي وملحق. الحوش الخلفي واسع ويستوعب جلسة خارجية.",
    descriptionEn:
      "On a 15 m street facing west, with an internal stair and an annex. The back yard is wide enough for an outdoor majlis.",
    daysAgo: 17,
    viewsThisWeek: 172,
  },
];

interface RawEnquiry {
  reference: string;
  /** Index into RAW_PROPERTIES, or null for a general enquiry. */
  propertyIndex: number | null;
  customerName: string;
  phone: string;
  email: string;
  message: string;
  contactPreference: ContactPreference;
  source: EnquirySource;
  status: EnquiryStatus;
  assignedTo: string | null;
  note?: string;
  hoursAgo: number;
  /** Hours from now until the viewing, when one is booked. */
  viewingInHours?: number;
}

const RAW_ENQUIRIES: RawEnquiry[] = [
  {
    reference: "ENQ-2041",
    propertyIndex: 0,
    customerName: "عبدالعزيز الدوسري",
    phone: "0500001204",
    email: "",
    message: "الشقة لسه متاحة؟ أبي أعاينها بكرة بعد العصر إذا يناسبكم.",
    contactPreference: "whatsapp",
    source: "website",
    status: "new",
    assignedTo: null,
    hoursAgo: 1,
  },
  {
    reference: "ENQ-2042",
    propertyIndex: 13,
    customerName: "Maha Al Sudairi",
    phone: "0500001318",
    email: "maha.s@example.com",
    message:
      "Is the price on the park-facing unit negotiable? We are cash buyers and can move quickly.",
    contactPreference: "phone",
    source: "website",
    status: "new",
    assignedTo: null,
    hoursAgo: 3,
  },
  {
    reference: "ENQ-2043",
    propertyIndex: 18,
    customerName: "فهد القحطاني",
    phone: "0500001477",
    email: "",
    message: "الفيلا محجوزة؟ حطوني في قائمة الانتظار لو سمحتم.",
    contactPreference: "whatsapp",
    source: "whatsapp",
    status: "new",
    assignedTo: null,
    hoursAgo: 5,
  },
  {
    reference: "ENQ-2044",
    propertyIndex: 30,
    customerName: "نورة العتيبي",
    phone: "0500001560",
    email: "noura.o@example.com",
    message: "أبي أعرف تكاليف الإفراغ والسعي قبل ما أقرر.",
    contactPreference: "email",
    source: "website",
    status: "new",
    assignedTo: null,
    hoursAgo: 7,
  },
  {
    reference: "ENQ-2045",
    propertyIndex: 25,
    customerName: "Samir Haddad",
    phone: "0500001631",
    email: "samir.h@example.com",
    message: "I want to open a clinic. Does the unit have a separate WC and water supply?",
    contactPreference: "whatsapp",
    source: "whatsapp",
    status: "contacted",
    assignedTo: "staff_mohammed",
    note: "رديت عليه، طلب مخطط المحل. أرسلته على واتساب.",
    hoursAgo: 22,
  },
  {
    reference: "ENQ-2046",
    propertyIndex: 2,
    customerName: "سلطان الحربي",
    phone: "0500001742",
    email: "",
    message: "الفيلا مناسبة، بس أبي أشوف الملحق قبل. متى أقدر أمر؟",
    contactPreference: "phone",
    source: "phone",
    status: "contacted",
    assignedTo: "staff_reem",
    note: "متاح الخميس فقط.",
    hoursAgo: 27,
  },
  {
    reference: "ENQ-2047",
    propertyIndex: 8,
    customerName: "Layla Rahman",
    phone: "0500001855",
    email: "layla.r@example.com",
    message: "Does the compound rent include maintenance, and is the pool shared?",
    contactPreference: "email",
    source: "website",
    status: "contacted",
    assignedTo: "staff_reem",
    hoursAgo: 31,
  },
  {
    reference: "ENQ-2048",
    propertyIndex: 3,
    customerName: "بدر الشمري",
    phone: "0500001966",
    email: "",
    message: "الدور الجديد كم آخر سعر؟ جاد وأقدر أفرغ هالأسبوع.",
    contactPreference: "whatsapp",
    source: "whatsapp",
    status: "viewing",
    assignedTo: "staff_mohammed",
    note: "المعاينة مؤكدة، المالك بيحضر.",
    hoursAgo: 48,
    viewingInHours: 26,
  },
  {
    reference: "ENQ-2049",
    propertyIndex: 19,
    customerName: "Hanan Al Zahrani",
    phone: "0500002071",
    email: "hanan.z@example.com",
    message: "We would like to see the fifth-floor unit on Saturday morning.",
    contactPreference: "phone",
    source: "website",
    status: "viewing",
    assignedTo: "staff_sara",
    hoursAgo: 52,
    viewingInHours: 44,
  },
  {
    reference: "ENQ-2050",
    propertyIndex: 12,
    customerName: "ماجد العنزي",
    phone: "0500002188",
    email: "",
    message: "الفيلا في العارض — أبي أعاينها مع الوالد.",
    contactPreference: "whatsapp",
    source: "walk-in",
    status: "viewing",
    assignedTo: "staff_reem",
    note: "زار المكتب اليوم الأول، جاد جدًا.",
    hoursAgo: 60,
    viewingInHours: 20,
  },
  {
    reference: "ENQ-2051",
    propertyIndex: 6,
    customerName: "تركي المطيري",
    phone: "0500002293",
    email: "turki.m@example.com",
    message: "أنهينا الإجراءات، شكرًا لكم على المتابعة.",
    contactPreference: "phone",
    source: "website",
    status: "closed",
    assignedTo: "staff_mohammed",
    note: "تم الإفراغ وسُلمت المفاتيح.",
    hoursAgo: 190,
  },
  {
    reference: "ENQ-2052",
    propertyIndex: 27,
    customerName: "Rania Kassem",
    phone: "0500002344",
    email: "rania.k@example.com",
    message: "Happy with the floor in Al Malqa — we're proceeding.",
    contactPreference: "email",
    source: "website",
    status: "closed",
    assignedTo: "staff_sara",
    note: "Transfer completed at the notary.",
    hoursAgo: 240,
  },
  {
    reference: "ENQ-2053",
    propertyIndex: 23,
    customerName: "خالد الرشيد",
    phone: "0500002456",
    email: "",
    message: "الفيلا تأجرت؟ كنت متردد وتأخرت.",
    contactPreference: "whatsapp",
    source: "whatsapp",
    status: "lost",
    assignedTo: "staff_reem",
    note: "الوحدة تأجرت قبل ما يقرر. عرضنا عليه بديل ما ناسبه.",
    hoursAgo: 300,
  },
  {
    reference: "ENQ-2054",
    propertyIndex: 7,
    customerName: "Omar Farouk",
    phone: "0500002567",
    email: "omar.f@example.com",
    message: "The monthly rent is above my budget — anything cheaper furnished?",
    contactPreference: "email",
    source: "website",
    status: "lost",
    assignedTo: "staff_sara",
    hoursAgo: 340,
  },
  {
    reference: "ENQ-2055",
    propertyIndex: null,
    customerName: "أبو ريان",
    phone: "0500002678",
    email: "",
    message:
      "زار المكتب ويدور أرض في النرجس أو القيروان، ٥٠٠ إلى ٧٠٠ متر، ميزانية مليونين.",
    contactPreference: "phone",
    source: "walk-in",
    status: "contacted",
    assignedTo: "staff_mohammed",
    note: "أرسلنا له GZ-1053 و GZ-1063.",
    hoursAgo: 70,
  },
  {
    reference: "ENQ-2056",
    propertyIndex: 15,
    customerName: "منيرة الغامدي",
    phone: "0500002789",
    email: "munira.g@example.com",
    message: "الشقة في الصحافة متاحة للإيجار من أول الشهر الجاي؟",
    contactPreference: "whatsapp",
    source: "website",
    status: "new",
    assignedTo: null,
    hoursAgo: 9,
  },
  {
    reference: "ENQ-2057",
    propertyIndex: 10,
    customerName: "Yousef Barakat",
    phone: "0500002891",
    email: "yousef.b@example.com",
    message: "Is the new apartment in Al Qirawan still at the listed price?",
    contactPreference: "whatsapp",
    source: "website",
    status: "contacted",
    assignedTo: "staff_sara",
    hoursAgo: 34,
  },
  {
    reference: "ENQ-2058",
    propertyIndex: 20,
    customerName: "عبدالله الزهراني",
    phone: "0500002903",
    email: "",
    message: "الدور الأرضي بحوش — كم الإيجار وهل يقبل دفعتين؟",
    contactPreference: "phone",
    source: "phone",
    status: "contacted",
    assignedTo: "staff_reem",
    hoursAgo: 41,
  },
  {
    reference: "ENQ-2059",
    propertyIndex: 16,
    customerName: "Ibrahim Nasser",
    phone: "0500003014",
    email: "ibrahim.n@example.com",
    message: "Asking about the showroom yield — can you share the current contract?",
    contactPreference: "email",
    source: "website",
    status: "viewing",
    assignedTo: "staff_mohammed",
    hoursAgo: 76,
    viewingInHours: 52,
  },
  {
    reference: "ENQ-2060",
    propertyIndex: 24,
    customerName: "أمل السبيعي",
    phone: "0500003125",
    email: "",
    message: "أول تملّك لي، ودي أفهم خطوات التمويل العقاري.",
    contactPreference: "whatsapp",
    source: "website",
    status: "new",
    assignedTo: null,
    hoursAgo: 4,
  },
  {
    reference: "ENQ-2061",
    propertyIndex: 4,
    customerName: "Nasser Al Otaibi",
    phone: "0500003236",
    email: "nasser.o@example.com",
    message: "Interested in the Al Arid plot. Is the 3,300 per m² firm?",
    contactPreference: "phone",
    source: "phone",
    status: "closed",
    assignedTo: "staff_sara",
    note: "Agreed at 3,200. Deposit paid.",
    hoursAgo: 400,
  },
];

function newId(): string {
  return crypto.randomUUID();
}

export function createSeedProperties(now: Date): Property[] {
  return RAW_PROPERTIES.map((raw) => {
    const createdAt = subDays(now, raw.daysAgo).toISOString();
    // A sold or rented unit was touched more recently than it was listed.
    const updatedAt =
      raw.status === "available"
        ? createdAt
        : subDays(now, Math.max(0, raw.daysAgo - 2)).toISOString();

    return {
      id: newId(),
      reference: raw.reference,
      title: { ar: raw.titleAr, en: raw.titleEn },
      description: { ar: raw.descriptionAr, en: raw.descriptionEn },
      type: raw.type,
      transaction: raw.transaction,
      district: raw.district,
      status: raw.status,
      priceSar: raw.priceSar,
      rentPeriod:
        raw.transaction === "rent" ? (raw.rentPeriod ?? "yearly") : null,
      areaSqm: raw.areaSqm,
      beds: raw.beds,
      baths: raw.baths,
      livingRooms: raw.livingRooms,
      floor: raw.floor ?? null,
      ageYears: raw.ageYears,
      furnished: raw.furnished ?? false,
      amenities: raw.amenities,
      featured: raw.featured ?? false,
      viewsThisWeek: raw.viewsThisWeek,
      createdAt,
      updatedAt,
    } satisfies Property;
  });
}

export function createSeedEnquiries(
  properties: Property[],
  now: Date,
): Enquiry[] {
  return RAW_ENQUIRIES.map((raw) => {
    const createdAt = subHours(now, raw.hoursAgo).toISOString();
    // A lead that has moved on was last touched somewhere after it arrived.
    const updatedAt =
      raw.status === "new"
        ? createdAt
        : subMinutes(now, Math.round(raw.hoursAgo * 12)).toISOString();

    return {
      id: newId(),
      reference: raw.reference,
      propertyId:
        raw.propertyIndex === null
          ? null
          : (properties[raw.propertyIndex]?.id ?? null),
      customerName: raw.customerName,
      phone: raw.phone,
      email: raw.email,
      message: raw.message,
      contactPreference: raw.contactPreference,
      source: raw.source,
      status: raw.status,
      assignedTo: raw.assignedTo,
      note: raw.note ?? "",
      viewingAt:
        raw.viewingInHours === undefined
          ? null
          : addHours(now, raw.viewingInHours).toISOString(),
      createdAt,
      updatedAt,
    } satisfies Enquiry;
  });
}

/** Where the running reference counters pick up after the seed. */
export const NEXT_PROPERTY_REFERENCE = 1073;
export const NEXT_ENQUIRY_REFERENCE = 2062;
